### ISSUE TITLE
这，封装不完全啊

### ISSUE THREAD

**Issue by MarkGor** [2723659854/message#1]
intent连接里需要手动改，你现在是hardCode的

**Comment by 2723659854** [comment]
不好意思，没注意，已经改好了

**Comment by 2723659854** [comment]
> intent连接里需要手动改，你现在是hardCode的

不好意思，没注意，已经改好了

**Comment by MarkGor** [comment]
> > intent连接里需要手动改，你现在是hardCode的
> 
> 不好意思，没注意，已经改好了

大哥您別這樣，我白嫖的都感覺不好意思了....
